import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
#
# SQLite: o banco é um arquivo na raiz do projeto (ignorado pelo git). Não há
# servidor para subir — `mix ash.setup` cria o arquivo e roda as migrations.
config :h_stock, Core.Repo,
  database: Path.expand("../h_stock_dev.db", __DIR__),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # SQLite serializa escritas: um pool grande não acelera nada e só aumenta a
  # briga pelo lock. Cinco conexões dão folga para as leituras.
  pool_size: 5,
  # `:immediate` pega o lock de escrita já no BEGIN. É o que garante que uma
  # venda leia o saldo que vai alterar: no modo padrão (`:deferred`) duas
  # transações leem juntas e a segunda só descobre o problema ao escrever.
  default_transaction_mode: :immediate

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :h_stock, Web.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9v/fP84JtmZlVvsCaNAjwP3ocHc1c5fVdD0fZWo9b5kISwwl2Ki1n5aQ9U/09OlX",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:h_stock, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:h_stock, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :h_stock, Web.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/web/router\.ex$",
      ~r"lib/web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :h_stock, dev_routes: true, token_signing_secret: "PLl5g7gIAESK1egcRnPoJvvDPJ8xuI/x"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# A verificação em duas etapas vale aqui como vale em produção — é assim que
# se percorre o login inteiro sem surpresa no dia do deploy. Para desligá-la
# numa sessão de trabalho pontual, sem tocar neste arquivo:
#
#     TOTP_REQUIRED=false mix phx.server
