defmodule Web.Endpoint do
  use Phoenix.Endpoint, otp_app: :h_stock

  # Sessão cifrada, não só assinada.
  #
  # A sessão carrega o token de autenticação, e durante a verificação em duas
  # etapas carrega também o token de um login que ainda não terminou. Com
  # `signing_salt` sozinho o conteúdo é apenas assinado — ilegível para
  # adulterar, mas perfeitamente legível para quem tem o cookie. Cifrando, o
  # token não fica ao alcance de quem só sabe a senha e ainda não passou pelo
  # segundo fator.
  @session_options [
    store: :cookie,
    key: "_h_stock_key",
    signing_salt: "gSWeTGEx",
    encryption_salt: "V2s0FvRHnQmXbTqA",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :h_stock,
    gzip: not code_reloading?,
    only: Web.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :h_stock
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug Web.Router
end
