defmodule Core.Repo.Migrations.InitialSqliteSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :totp_recovery_hashes, {:array, :text}, null: false, default: []
      add :totp_last_used_at, :utc_datetime_usec
      add :totp_confirmed_at, :utc_datetime_usec
      add :totp_secret, :binary
      add :hashed_password, :text, null: false
      add :active, :boolean, null: false
      add :dashboard_sections, {:array, :text}, null: false, default: []
      add :can_view_dashboard, :boolean, null: false
      add :can_manage_orders, :boolean, null: false
      add :can_manage_stock, :boolean, null: false
      add :role, :text, null: false
      add :name, :text, null: false
      # `collate: :nocase` na coluna, e não só no índice: é a colação declarada
      # da coluna que o `unique_index` abaixo herda. Sem ela "Maria" e "maria"
      # seriam dois logins diferentes — no Postgres quem garantia isso era o
      # tipo `citext`, que no SQLite não passa de um nome de tipo sem efeito.
      # O gerador de migrations do AshSqlite não emite `collate`; se um dia
      # esta coluna for regerada, esta linha precisa voltar à mão.
      add :nickname, :citext, null: false, collate: :nocase
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:nickname], name: "users_unique_nickname_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:stock_movements, primary_key: false) do
      add :order_id,
          references(:orders,
            column: :id,
            name: "stock_movements_order_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :user_id,
          references(:users, column: :id, name: "stock_movements_user_id_fkey", type: :uuid)

      add :batch_id,
          references(:stock_batches,
            column: :id,
            name: "stock_movements_batch_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          )

      add :product_id,
          references(:products,
            column: :id,
            name: "stock_movements_product_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :inserted_at, :utc_datetime_usec, null: false
      add :reason, :text
      add :total_cost, :decimal
      add :cost_per_gram, :decimal
      add :batch_balance_after, :decimal
      add :balance_after, :decimal, null: false
      add :grams, :decimal, null: false
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:stock_batches, primary_key: false) do
      add :user_id,
          references(:users, column: :id, name: "stock_batches_user_id_fkey", type: :uuid)

      add :product_id,
          references(:products,
            column: :id,
            name: "stock_batches_product_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :depleted_at, :utc_datetime_usec
      add :remaining_grams, :decimal, null: false
      add :initial_grams, :decimal, null: false
      add :cost_per_gram, :decimal, null: false
      add :label, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:products, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false
      add :min_stock_grams, :decimal, null: false
      add :stock_grams, :decimal, null: false
      add :price_per_gram, :decimal, null: false
      add :unit, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:stock_batches, ["product_id", "depleted_at"])

    create unique_index(:products, [:name], name: "products_unique_name_index")

    create table(:orders, primary_key: false) do
      add :driver_id,
          references(:users,
            column: :id,
            name: "orders_driver_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :user_id,
          references(:users,
            column: :id,
            name: "orders_user_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :delivered_at, :utc_datetime_usec
      add :out_for_delivery_at, :utc_datetime_usec
      add :assigned_at, :utc_datetime_usec
      add :delivery_lon, :decimal
      add :delivery_lat, :decimal
      add :delivery_address, :text
      add :delivery_status, :text, null: false
      add :cancelled_at, :utc_datetime_usec
      add :cost_total, :decimal, null: false
      add :total, :decimal, null: false
      add :discount_total, :decimal, null: false
      add :subtotal, :decimal, null: false
      add :discount_value, :decimal, null: false
      add :discount_type, :text, null: false
      add :status, :text, null: false
      add :note, :text
      add :customer_name, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:order_items, primary_key: false) do
      add :batch_id,
          references(:stock_batches,
            column: :id,
            name: "order_items_batch_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )

      add :product_id,
          references(:products,
            column: :id,
            name: "order_items_product_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_items_order_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :total_cost, :decimal, null: false
      add :cost_per_gram, :decimal, null: false
      add :batch_label, :text
      add :total, :decimal, null: false
      add :price_per_gram, :decimal, null: false
      add :grams, :decimal, null: false
      add :product_name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `order_items` table without the `order_items_order_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `order_items` table without the `order_items_product_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `order_items` table without the `order_items_batch_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:order_items)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_driver_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:orders)

    drop_if_exists unique_index(:products, [:name], name: "products_unique_name_index")

    drop_if_exists index(:stock_batches, ["product_id", "depleted_at"],
                     name: "stock_batches_product_id_depleted_at_index"
                   )

    drop table(:products)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `stock_batches` table without the `stock_batches_product_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `stock_batches` table without the `stock_batches_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:stock_batches)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `stock_movements` table without the `stock_movements_product_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `stock_movements` table without the `stock_movements_batch_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `stock_movements` table without the `stock_movements_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `stock_movements` table without the `stock_movements_order_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:stock_movements)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:nickname], name: "users_unique_nickname_index")

    drop table(:users)
  end
end
