defmodule Core.Repo.Migrations.AddTotp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :totp_secret, :binary
      add :totp_confirmed_at, :utc_datetime_usec
      add :totp_last_used_at, :utc_datetime_usec
      add :totp_recovery_hashes, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:users) do
      remove :totp_recovery_hashes
      remove :totp_last_used_at
      remove :totp_confirmed_at
      remove :totp_secret
    end
  end
end
