defmodule Core.Repo.Migrations.AddDeliveryTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :delivery_status, :text, null: false, default: "pending"
      add :out_for_delivery_at, :utc_datetime_usec
      add :delivered_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:orders) do
      remove :delivered_at
      remove :out_for_delivery_at
      remove :delivery_status
    end
  end
end
