defmodule Core.Repo.Migrations.AddOrderEdited do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :edited_at, :utc_datetime_usec

      add :edited_by_id,
          references(:users,
            column: :id,
            name: "orders_edited_by_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )
    end
  end

  def down do
    alter table(:orders) do
      remove :edited_by_id
      remove :edited_at
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_edited_by_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end
