defmodule Core.Repo.Migrations.AddDriverProfileAndDeliveryAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :can_manage_orders, :boolean, null: false, default: false
    end

    alter table(:orders) do
      add :delivery_address, :text
      add :delivery_lat, :decimal
      add :delivery_lon, :decimal
      add :assigned_at, :utc_datetime_usec

      add :driver_id,
          references(:users,
            column: :id,
            name: "orders_driver_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end
  end

  def down do
    drop constraint(:orders, "orders_driver_id_fkey")

    alter table(:orders) do
      remove :driver_id
      remove :assigned_at
      remove :delivery_lon
      remove :delivery_lat
      remove :delivery_address
    end

    alter table(:users) do
      remove :can_manage_orders
    end
  end
end
