defmodule Core.Repo.Migrations.AddAuditLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_entries, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "audit_entries_user_id_fkey",
            type: :uuid,
            on_delete: :nilify_all
          )

      add :inserted_at, :utc_datetime_usec, null: false
      add :user_name, :text
      add :details, :map, default: %{}
      add :summary, :text, null: false
      add :subject_label, :text, null: false
      add :subject_id, :uuid, null: false
      add :subject_type, :text, null: false
      add :action, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create index(:audit_entries, ["subject_type", "inserted_at"])

    create index(:audit_entries, ["inserted_at"])
  end

  def down do
    drop_if_exists index(:audit_entries, ["inserted_at"], name: "audit_entries_inserted_at_index")

    drop_if_exists index(:audit_entries, ["subject_type", "inserted_at"],
                     name: "audit_entries_subject_type_inserted_at_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `audit_entries` table without the `audit_entries_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:audit_entries)
  end
end
