defmodule Core.Repo.Migrations.AddDashboardPermissions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :can_view_dashboard, :boolean, null: false, default: false
      add :dashboard_sections, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:users) do
      remove :dashboard_sections
      remove :can_view_dashboard
    end
  end
end
