defmodule Core.Repo.Migrations.AddStockBatches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stock_movements) do
      add :batch_balance_after, :decimal
      add :cost_per_gram, :decimal
      add :total_cost, :decimal
      add :batch_id, :uuid
    end

    create table(:stock_batches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:stock_movements) do
      modify :batch_id,
             references(:stock_batches,
               column: :id,
               name: "stock_movements_batch_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:stock_batches) do
      add :label, :text, null: false
      add :cost_per_gram, :decimal, null: false
      add :initial_grams, :decimal, null: false
      add :remaining_grams, :decimal, null: false
      add :depleted_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id,
          references(:products,
            column: :id,
            name: "stock_batches_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "stock_batches_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:stock_batches, [:product_id, :depleted_at])

    alter table(:orders) do
      add :cost_total, :decimal, null: false, default: "0"
    end

    alter table(:order_items) do
      add :batch_label, :text
      add :cost_per_gram, :decimal, null: false, default: "0"
      add :total_cost, :decimal, null: false, default: "0"

      add :batch_id,
          references(:stock_batches,
            column: :id,
            name: "order_items_batch_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    flush()

    backfill()
  end

  # O estoque que já existia não tinha lote nem custo. Em vez de deixar
  # produto com saldo e nenhum lote de onde vender — e pedido antigo sem lote
  # para devolver no cancelamento —, cada produto ganha um lote "Estoque
  # anterior" com custo zero, para onde apontam o histórico e os itens já
  # vendidos. Custo zero é honesto: essa mercadoria entrou sem ninguém
  # informar quanto custou.
  defp backfill do
    execute("""
    INSERT INTO stock_batches (
      id, product_id, label, cost_per_gram, initial_grams, remaining_grams,
      depleted_at, inserted_at, updated_at
    )
    SELECT
      gen_random_uuid(),
      p.id,
      'Estoque anterior',
      0,
      GREATEST(p.stock_grams, 0),
      GREATEST(p.stock_grams, 0),
      CASE WHEN p.stock_grams > 0 THEN NULL ELSE (now() AT TIME ZONE 'utc') END,
      (now() AT TIME ZONE 'utc'),
      (now() AT TIME ZONE 'utc')
    FROM products p
    """)

    execute("""
    UPDATE stock_movements m
    SET batch_id = b.id,
        cost_per_gram = 0,
        total_cost = 0,
        batch_balance_after = m.balance_after
    FROM stock_batches b
    WHERE b.product_id = m.product_id
      AND b.label = 'Estoque anterior'
      AND m.batch_id IS NULL
    """)

    execute("""
    UPDATE order_items i
    SET batch_id = b.id,
        batch_label = 'Estoque anterior'
    FROM stock_batches b
    WHERE b.product_id = i.product_id
      AND b.label = 'Estoque anterior'
      AND i.batch_id IS NULL
    """)
  end

  def down do
    drop constraint(:order_items, "order_items_batch_id_fkey")

    alter table(:order_items) do
      remove :batch_id
      remove :total_cost
      remove :cost_per_gram
      remove :batch_label
    end

    alter table(:orders) do
      remove :cost_total
    end

    drop constraint(:stock_batches, "stock_batches_product_id_fkey")

    drop constraint(:stock_batches, "stock_batches_user_id_fkey")

    drop_if_exists index(:stock_batches, [:product_id, :depleted_at])

    alter table(:stock_batches) do
      remove :user_id
      remove :product_id
      remove :updated_at
      remove :inserted_at
      remove :depleted_at
      remove :remaining_grams
      remove :initial_grams
      remove :cost_per_gram
      remove :label
    end

    drop constraint(:stock_movements, "stock_movements_batch_id_fkey")

    alter table(:stock_movements) do
      modify :batch_id, :uuid
    end

    drop table(:stock_batches)

    alter table(:stock_movements) do
      remove :batch_id
      remove :total_cost
      remove :cost_per_gram
      remove :batch_balance_after
    end
  end
end
