defmodule Core.Repo.Migrations.AddInventoryAndOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :confirmed_at
      add :name, :text, null: false
      add :role, :text, null: false, default: "employee"
      add :can_manage_stock, :boolean, null: false, default: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:stock_movements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :grams, :decimal, null: false
      add :balance_after, :decimal, null: false
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :product_id, :uuid, null: false
      add :user_id, :uuid
      add :order_id, :uuid
    end

    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:stock_movements) do
      modify :product_id,
             references(:products,
               column: :id,
               name: "stock_movements_product_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "stock_movements_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:products) do
      add :name, :text, null: false
      add :unit, :text, null: false, default: "kg"
      add :price_per_gram, :decimal, null: false
      add :stock_grams, :decimal, null: false, default: "0"
      add :min_stock_grams, :decimal, null: false, default: "0"
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:products, [:name], name: "products_unique_name_index")

    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:stock_movements) do
      modify :order_id,
             references(:orders,
               column: :id,
               name: "stock_movements_order_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:orders) do
      add :customer_name, :text
      add :note, :text
      add :status, :text, null: false, default: "completed"
      add :discount_type, :text, null: false, default: "none"
      add :discount_value, :decimal, null: false, default: "0"
      add :subtotal, :decimal, null: false, default: "0"
      add :discount_total, :decimal, null: false, default: "0"
      add :total, :decimal, null: false, default: "0"
      add :cancelled_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "orders_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create table(:order_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :product_name, :text, null: false
      add :grams, :decimal, null: false
      add :price_per_gram, :decimal, null: false
      add :total, :decimal, null: false

      add :order_id,
          references(:orders,
            column: :id,
            name: "order_items_order_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :product_id,
          references(:products,
            column: :id,
            name: "order_items_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end
  end

  def down do
    drop constraint(:order_items, "order_items_order_id_fkey")

    drop constraint(:order_items, "order_items_product_id_fkey")

    drop table(:order_items)

    drop constraint(:orders, "orders_user_id_fkey")

    alter table(:orders) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :cancelled_at
      remove :total
      remove :discount_total
      remove :subtotal
      remove :discount_value
      remove :discount_type
      remove :status
      remove :note
      remove :customer_name
    end

    drop constraint(:stock_movements, "stock_movements_order_id_fkey")

    alter table(:stock_movements) do
      modify :order_id, :uuid
    end

    drop table(:orders)

    drop_if_exists unique_index(:products, [:name], name: "products_unique_name_index")

    alter table(:products) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :min_stock_grams
      remove :stock_grams
      remove :price_per_gram
      remove :unit
      remove :name
    end

    drop constraint(:stock_movements, "stock_movements_product_id_fkey")

    drop constraint(:stock_movements, "stock_movements_user_id_fkey")

    alter table(:stock_movements) do
      modify :user_id, :uuid
      modify :product_id, :uuid
    end

    drop table(:products)

    drop table(:stock_movements)

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :can_manage_stock
      remove :role
      remove :name
      add :confirmed_at, :utc_datetime_usec
    end
  end
end
