defmodule Core.Repo.Migrations.AddOrderPayment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :payment_due_on, :date
      add :paid_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:orders) do
      remove :paid_at
      remove :payment_due_on
    end
  end
end
